export const insults = {
  soft: [
    "Twoja stara klaszcze u Rubika.",
    "Jesteś bystry jak woda w klozecie po sraniu.",
    "Gdyby głupota miała skrzydła, latałbyś jak pierdolony Boeing.",
    "Wyglądasz jakby cię stado chujów w nocy podeptało.",
    "Masz ryj jak niewypał, lepiej nie dotykać.",
    "Twoje IQ jest niższe niż numer buta twojej starej.",
    "Jesteś tak potrzebny jak kurwie majtki.",
    "Twoja matka myje okna w kopalni.",
    "Słuchanie ciebie to jak sranie szkłem – bolesne i bez sensu.",
    "Jesteś dowodem na to, że ewolucja potrafi wrzucić wsteczny.",
    "Twoje żarty są tak czerstwe, że można nimi gwoździe wbijać.",
    "Wyglądasz jakbyś spierdolił się z dywanu na podłogę.",
    "Gdybyś był chlebem, byłbyś piętką, której nikt nie chce wpierdolić.",
    "Jesteś tak interesujący jak zeszłoroczny śnieg oszczany przez psa.",
    "Twoje życie jest tak puste, że echo w nim zdycha z głodu.",
    "Masz tyle rozumu co wentylator w dupie.",
    "Jesteś jak prezerwatywa z dziurą – bezużyteczny.",
    "Twoja głowa to pudełko po butach – puste i bezwartościowe.",
    "Gdyby głupota bolała, ty byś nie wyszedł z domu.",
    "Jesteś tak pusty, że echo w tobie umiera z nudów."
  ],
  medium: [
    "Wyglądasz jak pół dupy zza krzaka.",
    "Twoja twarz wygląda jakbyś gasił pożar łopatą, ty zjebie.",
    "Jesteś tak tępy, że nie potrafisz wylać wody z buta z instrukcją na podeszwie.",
    "Zamknij mordę, bo ci się zęby spocą.",
    "Jesteś pomyłką genetyczną, którą natura chce zapomnieć.",
    "Masz taki ryj, że nawet cebula by przy tobie zapłakała.",
    "Twoja stara miesza bigos łokciem.",
    "Jesteś tak brzydki, że wchodzisz do domu przez Wi-Fi, żeby nie straszyć domowników.",
    "Gdyby twoja dupa była tak pojemna jak twoja głupota, srałbyś meblami.",
    "Twoje narodziny to był pierwszy krok do zagłady ludzkości.",
    "Nie mów tyle, bo ci się morda zmęczy od pierdolenia głupot.",
    "Jesteś jak wrzód na dupie – upierdliwy i niepotrzebny.",
    "Turlaj dropsa, frajerze.",
    "Wyglądasz jakbyś zamiast mózgu miał styropian.",
    "Twoja matka klaszcze czołem.",
    "Masz więcej sensu w oczach niż w głowie.",
    "Jesteś jak filtr kawy – przejrzysty i bezwartościowy.",
    "Twoja inteligencja jest jak bateria telefonu – szybko się rozładowuje.",
    "Gdybyś był owocem, byłbyś cytryną bez soku.",
    "Jesteś tak gęsty, że w tobie tonie powietrze."
  ],
  hard: [
    "Jesteś takim zjebem, że nawet twój stary żałuje, że nie strzelił w prześcieradło.",
    "Chuj ci w dupę i kotwicę w plecy, żebyś się kurwo nie cofał.",
    "Wyglądasz jak wyskrobany, a nie urodzony.",
    "Twoja morda pasuje do krocza jak ulał, chuju.",
    "Sraj się psie, bo na szczekanie już za późno.",
    "Jesteś tak spierdolony, że psychiatrzy piszą o tobie doktoraty.",
    "Twoja stara to kopara, a twój stary ją odpala.",
    "Zaraz ci tak przyjebię, że ci się ewolucja cofnie do małpy.",
    "Masz mózg wielkości orzecha, i to laskowego, ty debilu.",
    "Jesteś odpadem nuklearnym społeczeństwa.",
    "Wypierdalaj stąd, zanim cię rzeczywistość zweryfikuje butem na ryju.",
    "Twoja egzystencja to obraza dla godności ludzkiej.",
    "Jesteś jak dziura w kondomie – wpadka, której nikt nie chciał.",
    "Gdybyś miał grosz za każde mądre słowo, byłbyś, kurwa, bankrutem.",
    "Twoja twarz to najlepszy środek antykoncepcyjny.",
    "Powinieneś być w muzeum jako eksponat głupoty.",
    "Jesteś jak choroba weneryczna – bolesny i wstydliwy.",
    "Twoja głowa to jest jak pusta szuflada – nic w niej nie ma.",
    "Gdybyś był bronią, byłbyś pistoletem na wodę.",
    "Jesteś bardziej bezużyteczny niż ciąg na kiblu.",
    "Twoja mama jest tak tłusta, że ma własny kod pocztowy.",
    "Jesteś tak głupi, że myślisz, że antykoncepcja to tabletka po orgazmie.",
    "Masz takiego małego kutasa, że jak sikasz to musisz się podpierać.",
    "Wyglądasz jak po przejściu przez betoniarkę… od środka.",
    "Twoja siostra ssie lepiej niż odkurzacz przemysłowy.",
    "Jesteś tak brzydki, że twoje selfie crashuje apkę.",
    "Twoja dupa wygląda jak zgnieciony kebab po imprezie.",
    "Gdyby twoja mama była grą, to byłaby darmowa na PornHubie.",
    "Jesteś tak głupi, że kawę pijesz widelcem.",
    "Twoje życie to taki fail, że nawet memy się z ciebie śmieją.",
    "Masz mordę jak rozjebany kapeć po maratonie w błocie.",
    "Twoja mama robi loda za paczkę fajek i resztę z Biedry.",
    "Jesteś tak cienki, że w cieniu się chowasz przed słońcem.",
    "Twoja cipka śmierdzi jak śmietnik w sierpniu po tygodniu upałów.",
    "Wyglądasz jak model przed i po… i to to „po” jest z horroru.",
    "Jesteś tak wolny, że broadband ci zazdrości.",
    "Twoja rodzina to taki chów wsobny, że nawet psy się brzydzą.",
    "Masz charakter jak mokra szmata – śmierdzi i nic nie trzyma.",
    "Gdyby twoja głupota miała zapach, oddychalibyśmy przez maskę gazową.",
    "Twoja mama jest tak popularna, że ma własną kolejkę w kolejce po socjal.",
    "Jesteś tak żałosny, że nawet twoja depresja ma depresję.",
    "Twoja dupa to taki krater, że NASA chce tam sondę wysłać.",
    "Masz twarz jak po zderzeniu z betoniarką i przegraną walce z glebą.",
    "Twoja mama tak lubi fiuty, że ma kolekcję jak filatelista znaczki.",
    "Jesteś tak głupi, że myślisz, że 69 to numer autobusu."
  ],
  extreme: [
    "Jesteś tak głupi, że jak byś spadł z dupy to byś się zabił o własny kręgosłup.",
    "Twoja mama tak szeroko rozkłada nogi, że Google Maps ma ją w warstwie ulic.",
    "Wyglądasz jak ktoś, kogo abortowano za późno… i to widać.",
    "Masz twarz, którą nawet piesek liznąłby tylko przez przypadek.",
    "Jesteś tak brzydki, że jak poszedłeś do kina na horror, ludzie uciekli z sali.",
    "Twoje krocze śmierdzi tak, że komary wolą malarię.",
    "Gdyby głupota była prądem, świeciłbyś jaśniej niż Czarnobyl.",
    "Twoja rodzina to takie kazirodztwo, że drzewo genealogiczne wygląda jak pączek.",
    "Jesteś tak cienki, że jak się obrócisz bokiem to znikasz z radaru Tinder.",
    "Twoja dupa jest tak rozjebana, że mogłaby służyć jako tunel metra.",
    "Wyglądasz jak efekt uboczny po zażyciu całej apteki na raz.",
    "Twoja inteligencja to oksymoron – sama w sobie jest sprzecznością.",
    "Jesteś tak żałosny, że nawet twoje łzy mają depresję.",
    "Gdybyś był rośliną, to nawet chwasty by cię olały.",
    "Twoja mama sprzedaje dupę taniej niż promocja w Biedronce.",
    "Masz osobowość jak zużyta prezerwatywa – nikt cię nie chce.",
    "Jesteś tak wolny, że żółw z połamaną nogą cię wyprzedza.",
    "Twoja twarz to dowód, że natura czasem robi błędy drukarskie.",
    "Gdyby głupota bolała, wyłbyś jak suka w rui 24/7.",
    "Jesteś tak bezwartościowy, że nawet orgazm z tobą to strata czasu.",
    "Wyglądasz jak ktoś, komu natura powiedziała „fuck this shit” i poszła pić.",
    "Twoje życie to taki cringe, że TikTok by cię zbanował za second-hand wstyd.",
    "Twoja siostra rucha się taniej niż promocja kebaba o 3 w nocy.",
    "Jesteś tak brzydki, że nawet filtr „beauty” na snapie się crashuje.",
    "Twoja mama ma więcej km na liczniku niż tir na autostradzie A2.",
    "Masz kutasa jak guzik od windy – nikt go nie zauważa.",
    "Jesteś tak głupi, że jak ktoś mówi „myśl”, to ty słyszysz „miś”.",
    "Twoja dupa jest tak wielka, że ma własną grawitację.",
    "Wyglądasz jak po 15 latach picia denaturatu i paleniu opon.",
    "Twoja mama jest tak szeroka, że ma własny pas startowy.",
    "Jesteś tak bezużyteczny, że nawet wirusy cię omijają.",
    "Twoja inteligencja to poziom „roślina doniczkowa po podlaniu solą”.",
    "Masz mordę, którą nawet Photoshop odmawia ratować.",
    "Twoja rodzina to taki burdel, że nawet alfons ma dość.",
    "Jesteś tak żałosny, że nawet boty na Omegle cię kickują.",
    "Twoja mama tak lubi ruchać, że ma kartę stałego klienta w przychodni.",
    "Jesteś tak głupi, że myślisz, że prezerwatywa to czapka na kutasa.",
    "Wyglądasz jak model z kampanii „nie bierz narkotyków – patrz co się dzieje”.",
    "Twoja dupa to taki black hole, że światło się w niej gubi.",
    "Masz osobowość jak zgniły śledź – śmierdzi i nikt nie chce dotykać.",
    "Jesteś tak brzydki, że twoje dzieci będą wyglądać lepiej jak adoptowane.",
    "Twoja mama sprzedaje dupsko taniej niż promocja na parówki w Lidlu.",
    "Jesteś tak wolny, że żółwie robią sobie z ciebie memy.",
    "Twoje życie to taki shitshow, że nawet kupa ma lepszy scenariusz.",
    "Masz twarz jak po zderzeniu z pługiem śnieżnym i betonem jednocześnie.",
    "Jesteś jebanym błędem systemu, którego nawet format C: nie naprawi.",
    "Twoja stara cię w betoniarce kołysała, dlatego jesteś taki twardy debil.",
    "Wyglądasz jakbyś był dzieckiem kazirodczego związku klauna z małpą.",
    "Chuj ci w oko, żebyś, kurwa, widział jak cię dymają.",
    "Jesteś takim śmieciem, że nawet śmieciarka by cię nie zabrała.",
    "Powinieneś nosić roślinę w doniczce, żeby nadrabiać tlen, który marnujesz, ty kurwo.",
    "Twoje DNA to jebane spaghetti code, którego nikt nie chce tknąć.",
    "Jesteś tak obrzydliwy, że lustra pękają na twój widok ze wstydu.",
    "Jak cię walnę w ten głupi łeb, to ci się te resztki mózgu zlasują.",
    "Jesteś pierdoloną pomyłką, którą należy zutylizować.",
    "Twoje życie to jebany żart, z którego nikt się nie śmieje.",
    "Wypierdalaj do szamba, tam gdzie twoje miejsce, szczurze.",
    "Jesteś tak chujowy, że brakuje skali w dupie.",
    "Twoja stara to chyba walec, bo jesteś taki płaski umysłowo.",
    "Zgiń, przepadnij, spierdalaj – w dowolnej kolejności, byle szybko.",
    "Jesteś bardziej zużyty niż prezerwatywa na gównianym weselu.",
    "Twoja głowa to tak pusta, że echo tam umiera z głodu.",
    "Gdyby głupość była przestępstwem, dostałbyś dożywocie.",
    "Jesteś odpadem który nawet śmieci się wstydzą.",
    "Twoja egzystencja to błąd w matrycy, który trzeba usunąć."
  ]
}

export const questions = [
  "No dawaj kurwa, kliknij.",
  "Masz jaja czy pizdę?",
  "Chcesz się popłakać?",
  "Zniszczyć ci psychikę?",
  "Pokaż ryj, to cię wyjaśnię.",
  "Gotowy na wpierdol słowny?",
  "Jesteś pewien, że chcesz tego?",
  "Sprawdźmy czy wytrzymasz",
  "Chcesz usłyszeć prawdę?",
  "Masz odwagę na więcej?",
  "Przygotuj się na ostrześliwość",
  "Czas na brutalną szczerość"
]
